<script src="<?=base_url();?>assets/back/js/accordion.js"></script>
<script src="<?=base_url();?>assets/back/js/app.js"></script>
<script src="<?=base_url();?>assets/back/js/bootstrap.js"></script>
<script src="<?=base_url();?>assets/back/js/chart.js"></script>
<script src="<?=base_url();?>assets/back/js/chat.js"></script>
<script src="<?=base_url();?>assets/back/js/copy-code.js"></script>
<script src="<?=base_url();?>assets/back/js/dark-mode-switcher.js"></script>
<script src="<?=base_url();?>assets/back/js/datatable.js"></script>
<script src="<?=base_url();?>assets/back/js/datepicker.js"></script>
<script src="<?=base_url();?>assets/back/js/dropdown.js"></script>
<script src="<?=base_url();?>assets/back/js/dropzone.js"></script>
<script src="<?=base_url();?>assets/back/js/feather.js"></script>
<script src="<?=base_url();?>assets/back/js/helper.js"></script>
<script src="<?=base_url();?>assets/back/js/highlight.js"></script>
<script src="<?=base_url();?>assets/back/js/image-zoom.js"></script>
<script src="<?=base_url();?>assets/back/js/maps.js"></script>
<script src="<?=base_url();?>assets/back/js/mobile-menu.js"></script>
<script src="<?=base_url();?>assets/back/js/modal.js"></script>
<script src="<?=base_url();?>assets/back/js/search.js"></script>
<script src="<?=base_url();?>assets/back/js/select2.js"></script>
<script src="<?=base_url();?>assets/back/js/show-code.js"></script>
<script src="<?=base_url();?>assets/back/js/show-modal.js"></script>
<script src="<?=base_url();?>assets/back/js/side-menu-tooltip.js"></script>
<script src="<?=base_url();?>assets/back/js/slick.js"></script>
<script src="<?=base_url();?>assets/back/js/summernote.js"></script>
<script src="<?=base_url();?>assets/back/js/svg-loader.js"></script>
<script src="<?=base_url();?>assets/back/js/tab.js"></script>
<script src="<?=base_url();?>assets/back/js/toast.js"></script>
<script src="<?=base_url();?>assets/back/js/tooltipster.js"></script>
<script src="<?=base_url();?>assets/back/js/validation.js"></script>
<script src="<?=base_url();?>assets/back/js/apps.js"></script>